const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
class Local extends ResourceLoader {fetch(url){const p=path.resolve(__dirname,'../dist','.'+new URL(url).pathname);return Promise.resolve(fs.readFileSync(p));}}
async function open(saved){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(fs.readFileSync(path.resolve(__dirname,'../dist/index.html'),'utf8'),{url:'https://battle.test/',runScripts:'dangerously',resources:new Local(),virtualConsole:vc,beforeParse(w){w.confirm=()=>true;w.alert=x=>errors.push('alert: '+x);if(saved)w.localStorage.setItem('battle-desk-v1',saved);}});await new Promise(resolve=>dom.window.addEventListener('load',()=>setTimeout(resolve,100)));assert.ok(dom.window.BattleDesk,'App initialized: '+errors.join('; ')+' / '+dom.window.document.querySelector('#desk-notice')?.textContent);return {dom,w:dom.window,errors};}
(async()=>{let {dom,w,errors}=await open();let $=w.$,app=w.BattleDesk;console.log('Initialization notice:', $('#desk-notice').text());assert.equal(app.getState().teams[0].filter(Boolean).length,6,'seed has six');assert.equal($('#p1 .level').val(),'50');assert.equal($('#p1 .item').val(),'Choice Scarf');
const select=(name)=>{$('#p2 input.set-selector').val(name+' ('+Object.keys(w.setdex[name])[0]+')').trigger('change');};select('Gastrodon');$('#p2 .item').val('Leftovers').trigger('change');$('#p2 .move1 .move-selector').val('Earth Power').trigger('change');$('#p2 .percent-hp').val(43).trigger('change');$('#p2 .sa .boost').val('2').trigger('change');$('#p2 .status').val('Burned').trigger('change');$('#rival-note').val('Tierra confirmado').trigger('input');$('.checks input').eq(1).prop('checked',true).trigger('change');const hp=$('#p2 .current-hp').val(),first=app.getState().teams[1][0];app.switchSlot(1,1);select('Scizor');app.switchSlot(1,0);assert.equal($('#p2 .item').val(),'Leftovers');assert.equal($('#p2 .move1 .move-selector').val(),'Earth Power');assert.equal($('#p2 .current-hp').val(),hp,'exact HP survives switches');assert.equal($('#p2 .sa .boost').val(),'2');assert.equal($('#p2 .status').val(),'Burned');assert.equal($('#rival-note').val(),'Tierra confirmado');assert.equal(app.getState().teams[1][0].confirmed[1],true);assert.ok(!$('#mainResult').text().includes('No se pudo calcular'));assert.ok(w.damageResults[0][0].range()[1]>0,'real damage calculated');
const saved=JSON.stringify(app.getState());dom.window.close();({dom,w,errors}=await open(saved));$=w.$;app=w.BattleDesk;assert.equal($('#p2 .current-hp').val(),hp,'reload HP');assert.equal($('#p2 .status').val(),'Burned');assert.equal($('#rival-note').val(),'Tierra confirmado');assert.equal($('#p1 .item').val(),'Choice Scarf','custom set reload');app.switchSlot(0,1);assert.equal($('#p1 .sp .ivs').val(),'0');assert.equal($('#p1 .item').val(),'Rocky Helmet');app.switchSlot(0,0);
assert.throws(()=>app.parseTeam('Missingno\n- Tackle'));assert.throws(()=>app.parseTeam('Garchomp\nEVs: 252 HP / 252 Atk / 252 Spe'));assert.throws(()=>app.switchSlot(1,7));assert.throws(()=>app.validate({version:1}));
$('#new-battle').click();assert.equal(app.getState().teams[1].filter(Boolean).length,0);assert.equal(app.getState().teams[0].filter(Boolean).length,6);$('#undo').click();assert.equal(app.getState().teams[1][0].note,'Tierra confirmado');assert.equal($('#p2 .current-hp').val(),hp);assert.equal($('#p2 .sa .boost').val(),'2');
app.importTeam('Gengar @ Life Orb\nAbility: Levitate\nEVs: 252 SpA / 4 SpD / 252 Spe\nTimid Nature\n- Shadow Ball',1);assert.equal(app.getState().teams[1][0].name,'Gengar');assert.equal(app.getState().teams[1].filter(Boolean).length,1);assert.equal($('#p2 .level').val(),'50');assert.equal($('#p2 .item').val(),'Life Orb');
const calc=w.calc;const a=new calc.Pokemon(5,'Garchomp',{level:50,evs:{atk:252},nature:'Jolly'}),b=new calc.Pokemon(5,'Heatran',{level:50,evs:{hp:252}});const result=calc.calculate(5,a,b,new calc.Move(5,'Earthquake'));assert.ok(result.range()[0]>b.maxHP());console.log('PASS: six slots; HP, item, moves, boosts, status, notes, confirmed flags; reload; seed; invalid input; new battle and undo; import; damage engine.');assert.deepEqual(errors,[],'No runtime errors');dom.window.close();})().catch(e=>{console.error(e);process.exit(1);});
