/* Session layer. Calculator and community mechanics retain their MIT license. */
$(function () {
 'use strict';
 if (!document.getElementById('p1') || !document.getElementById('p2')) return;
 var KEY='battle-desk-v1', busy=true, timer, undo=null, baselineField;
 var state={version:1,teams:[Array(6).fill(null),Array(6).fill(null)],active:[0,0],field:null};
 var sides=[$('#p1'),$('#p2')];
 function clone(x){return JSON.parse(JSON.stringify(x));}
 function message(x){$('#desk-notice').text(x);}
 function controls(root){return root.find('input,select').filter(function(){return !$(this).closest('.select2-container,.select2-drop,.desk-extra').length && !$(this).is('#importedSets');});}
 function capture(root){return controls(root).map(function(){return {v:$(this).val(),c:!!this.checked};}).get();}
 function apply(root,values){controls(root).each(function(i){if(!values[i])return;$(this).val(values[i].v);if(this.type==='checkbox'||this.type==='radio')this.checked=values[i].c;});}
 function refreshWidgets(root){root.find('input,select').each(function(){if($(this).data('select2'))$(this).select2('val',$(this).val());});}
 function snapshot(side){var p=sides[side],previous=state.teams[side][state.active[side]],pokemon=createPokemon(p);return {set:p.find('input.set-selector').val(),values:capture(p),name:pokemon.name,hp:Number(p.find('.percent-hp').val()),maxHP:pokemon.maxHP(),note:previous?previous.note:'',confirmed:previous?previous.confirmed:[false,false,false,false,false]};}
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));$('#save-state').text('Guardado en este navegador');}catch(e){$('#save-state').text('No se pudo guardar');message('El navegador bloqueó el guardado. Descarga una copia antes de cerrar.');}}
 function save(){if(busy)return;clearTimeout(timer);for(var s=0;s<2;s++)if(state.teams[s][state.active[s]])state.teams[s][state.active[s]]=snapshot(s);state.field=capture($('.field-info'));persist();render();}
 function later(){if(!busy){clearTimeout(timer);timer=setTimeout(save,100);}}
 function load(side,entry){var p=sides[side];if(!entry){p.addClass('empty-slot');return;}p.removeClass('empty-slot');p.find('input.set-selector').val(entry.set).trigger('change');apply(p,entry.values);p.find('.move-selector').trigger('change');apply(p,entry.values);p.find('.max-hp').attr('data-prev',entry.maxHP);p.find('.current-hp').attr('data-set',true);calcStats(p);calcHP(p);totalEVs(p);refreshWidgets(p);}
 function switchSlot(side,index){if((side!==0&&side!==1)||!Number.isInteger(index)||index<0||index>5)throw Error('Espacio inválido');save();busy=true;var field=capture($('.field-info'));state.active[side]=index;load(side,state.teams[side][index]);apply($('.field-info'),field);refreshWidgets($('.field-info'));busy=false;save();render();performCalculations();}
 function render(){for(var s=0;s<2;s++){var row=$('#roster-'+s).empty();state.teams[s].forEach(function(p,i){var b=$('<button type="button" class="slot">').toggleClass('active',i===state.active[s]).attr('aria-pressed',String(i===state.active[s])).attr('aria-label',(s?'Rival ':'Mi Pokémon ')+(i+1)+': '+(p?p.name:'vacío'));$('<span class="slot-number">').text(String(i+1).padStart(2,'0')).appendTo(b);$('<strong>').text(p?p.name:'+ Añadir').appendTo(b);$('<small>').text(p?(p.hp===0?'Debilitado':p.hp+'% PS'):'Elegir set').appendTo(b);if(p)$('<div class="hp-bar">').append($('<i>').css('width',Math.max(0,Math.min(100,p.hp))+'%')).appendTo(b);b.on('click',switchSlot.bind(null,s,i));row.append(b);});sides[s].toggleClass('empty-slot',!state.teams[s][state.active[s]]);}
  sides.forEach(function(p,s){if(!state.teams[s][state.active[s]])p.find('.select2-chosen').first().text('Buscar Pokémon y set…');});
  var e=state.teams[1][state.active[1]];if(document.activeElement!==document.getElementById('rival-note'))$('#rival-note').val(e?e.note:'');$('#rival-note,.checks input').prop('disabled',!e);$('.checks input').each(function(i){this.checked=!!(e&&e.confirmed[i]);});$('#undo').prop('disabled',!undo);
 }
 var originalCalc=performCalculations;
 performCalculations=function(){if(!state.teams[0][state.active[0]]||!state.teams[1][state.active[1]]){$('.move-result-group,.big-text,.small-text').addClass('desk-hidden');$('#speed-summary').text('Selecciona un espacio rival y busca su Pokémon en el panel derecho.');return;}$('.move-result-group,.big-text,.small-text').removeClass('desk-hidden');try{originalCalc();var a=damageResults[0][0].attacker,b=damageResults[1][0].attacker;$('#speed-summary').text('Velocidad: '+a.name+' '+a.stats.spe+' · '+b.name+' '+b.stats.spe+' — '+(a.stats.spe===b.stats.spe?'empate':(a.stats.spe>b.stats.spe?a.name:b.name)+' es más rápido')+'. Sin considerar prioridad.');}catch(e){$('#mainResult').text('No se pudo calcular con estos valores. Revisa el set y los movimientos.');}};
 $('.wrapper').prepend('<section class="desk-toolbar"><div><h1>Mesa de combate</h1><p>Tu equipo a la izquierda. Cada rival conserva sus cambios.</p></div><div class="desk-actions"><button id="import-team">Importar equipo</button><button id="backup">Copia de seguridad</button><button id="restore">Restaurar copia</button><button id="undo" disabled>Deshacer reinicio</button><button id="new-battle" class="primary">Nueva batalla</button></div></section><section class="desk-rosters"><div><div class="roster-head"><h2>MI EQUIPO</h2><small>Alt + 1–6</small></div><div class="slot-row" id="roster-0"></div></div><div class="rivals"><div class="roster-head"><h2>EQUIPO RIVAL</h2><small>Shift + 1–6</small></div><div class="slot-row" id="roster-1"></div></div></section><div class="desk-notice" id="desk-notice" role="status">Los sets iniciales son hipótesis, no datos conocidos del rival. Confirma lo que observes.</div><div class="desk-notes"><label>Notas del rival seleccionado<input id="rival-note" maxlength="500" placeholder="Ej.: parece Scarf; mostró Terremoto…"></label><div class="checks" title="M1–M4: movimientos confirmados en el orden del panel rival"><label><input type="checkbox"> Objeto visto</label><label><input type="checkbox"> M1</label><label><input type="checkbox"> M2</label><label><input type="checkbox"> M3</label><label><input type="checkbox"> M4</label></div></div><div class="desk-summary" id="speed-summary"></div>');
 var panels=$('<section class="desk-panels">'),nativePanels=$('.wrapper > .panel');nativePanels.eq(1).addClass('field-panel');nativePanels.first().before(panels);panels.append(nativePanels);sides[0].find('legend').first().text('Tu Pokémon');sides[1].find('legend').first().text('Pokémon rival');$('.poke-import').closest('[role=region]').hide();
 sides.forEach(function(p,s){p.find('.set-selector').attr('aria-label',s?'Buscar Pokémon rival y set':'Buscar tu Pokémon y set');var buttons=$('<div class="desk-extra"><button type="button" data-act="heal">PS 100%</button><button type="button" data-act="ko">Debilitado</button><button type="button" data-act="boost">Quitar boosts</button><button type="button" data-act="remove" class="danger">Vaciar espacio</button></div>');p.prepend(buttons);buttons.on('click','button',function(){if(!state.teams[s][state.active[s]])return;var action=$(this).data('act');if(action==='remove'){if(!confirm('¿Vaciar únicamente este espacio?'))return;state.teams[s][state.active[s]]=null;render();persist();performCalculations();return;}if(action==='boost')p.find('.boost').val(0).trigger('change');else p.find('.percent-hp').val(action==='heal'?100:0).trigger('change');save();performCalculations();});});
 $('body').append('<dialog id="import-dialog" class="desk-dialog"><h2>Importar equipo</h2><p>Pega hasta seis Pokémon en formato Showdown. Si omites el nivel, se usará 50. Reemplaza únicamente el equipo elegido.</p><label>Destino <select id="import-side"><option value="0">Mi equipo</option><option value="1">Equipo rival</option></select></label><textarea id="team-text" aria-label="Equipo en formato Showdown" spellcheck="false" placeholder="Garchomp @ Choice Scarf&#10;Ability: Rough Skin&#10;EVs: 252 Atk / 4 Def / 252 Spe&#10;Jolly Nature&#10;- Earthquake"></textarea><p id="import-error" class="error" role="alert"></p><div class="desk-actions"><button id="cancel-import">Cancelar</button><button id="confirm-import" class="primary">Reemplazar equipo</button></div></dialog><input id="backup-file" type="file" accept="application/json,.json" hidden>');
 function parseTeam(text){var blocks=text.trim().split(/\n\s*\n/);if(!text.trim()||blocks.length>6)throw Error('Introduce entre uno y seis Pokémon separados por una línea vacía.');var stats={HP:'hp',Atk:'at',Def:'df',SpA:'sa',SpD:'sd',Spe:'sp'};return blocks.map(function(block){var lines=block.trim().split('\n').map(function(x){return x.trim();}),head=lines.shift().split('@'),name=head[0].trim().replace(/ \([MF]\)$/,'');var nickname=name.match(/\(([^)]+)\)$/);if(nickname)name=nickname[1];if(!pokedex[name])throw Error('Pokémon no disponible: '+name);var set={level:50,evs:{},ivs:{},moves:[],nature:'Serious',item:head[1]?head[1].trim():'',ability:pokedex[name].abilities[0]};
   lines.forEach(function(line){if(!line)return;if(line.startsWith('- ')){var move=line.slice(2).replace(/Hidden Power \[([^\]]+)\]/,'Hidden Power $1');if(!moves[move])throw Error('Movimiento no disponible: '+move);set.moves.push(move);}else if(line.startsWith('Ability: '))set.ability=line.slice(9);else if(line.startsWith('Level: ')){set.level=Number(line.slice(7));if(!Number.isInteger(set.level)||set.level<1||set.level>100)throw Error('Nivel inválido.');}else if(/ Nature$/.test(line)){set.nature=line.replace(/ Nature$/,'');if(!calc.NATURES[set.nature])throw Error('Naturaleza inválida: '+set.nature);}else if(/^(EVs|IVs):/.test(line)){var iv=line.startsWith('IVs');line.slice(4).split('/').forEach(function(part){var m=part.trim().match(/^(\d+)\s+(HP|Atk|Def|SpA|SpD|Spe)$/);if(!m||Number(m[1])>(iv?31:252))throw Error('EVs/IVs inválidos: '+part);set[iv?'ivs':'evs'][stats[m[2]]]=Number(m[1]);});}else if(!/^(Shiny:|Happiness:|Gender:)/.test(line))throw Error('Línea no reconocida: '+line);});if(set.moves.length>4)throw Error(name+': máximo cuatro movimientos.');if(Object.values(set.evs).reduce(function(a,b){return a+b;},0)>510)throw Error(name+': los EVs exceden 510.');if(set.item&&items.indexOf(set.item)<0)throw Error('Objeto no disponible: '+set.item);if(abilities.indexOf(set.ability)<0)throw Error('Habilidad no disponible: '+set.ability);return {name:name,set:set};});}
 function importTeam(text,side){if(side!==0&&side!==1)throw Error('Equipo inválido');var parsed=parseTeam(text),field=capture($('.field-info')),old=clone(state);busy=true;try{var entries=parsed.map(function(x,i){var id='Battle Desk '+side+' '+i;setdex[x.name]=setdex[x.name]||{};setdex[x.name][id]=x.set;sides[side].find('input.set-selector').val(x.name+' ('+id+')').trigger('change');var e=snapshot(side);e.note='';e.confirmed=[false,false,false,false,false];return e;});state.teams[side]=entries.concat(Array(6-entries.length).fill(null));state.active[side]=0;load(side,state.teams[side][0]);apply($('.field-info'),field);}catch(e){state=old;load(side,state.teams[side][state.active[side]]);throw e;}finally{busy=false;}save();performCalculations();}
 $('#import-team').on('click',function(){$('#import-error').text('');document.getElementById('import-dialog').showModal();});$('#cancel-import').on('click',function(){document.getElementById('import-dialog').close();});$('#confirm-import').on('click',function(){try{var side=Number($('#import-side').val());parseTeam($('#team-text').val());if(!confirm('¿Reemplazar los seis espacios de '+(side?'rivales':'tu equipo')+'?'))return;importTeam($('#team-text').val(),side);document.getElementById('import-dialog').close();message('Equipo importado. Puedes modificar cualquier set y se guardará automáticamente.');}catch(e){$('#import-error').text(e.message);}});
 $('#rival-note').on('input',function(){var e=state.teams[1][state.active[1]];if(e){e.note=this.value;persist();}});$('.checks input').on('change',function(){var e=state.teams[1][state.active[1]];if(e){e.confirmed=$('.checks input').map(function(){return this.checked;}).get();persist();}});
 sides.forEach(function(p,s){p.find('input.set-selector').on('change.desk',function(){if(busy)return;p.find('.level').val(50).trigger('change');state.teams[s][state.active[s]]=snapshot(s);state.teams[s][state.active[s]].note='';state.teams[s][state.active[s]].confirmed=[false,false,false,false,false];save();performCalculations();});p.on('input change','input,select',later);});$('.field-info').on('input change','input,select',later);
 $('#new-battle').on('click',function(){if(!confirm('¿Empezar otra batalla? Se vacían los rivales y el campo; tu equipo vuelve a PS completos, sin estados ni boosts.'))return;save();undo=clone(state);busy=true;state.teams[1]=Array(6).fill(null);state.active[1]=0;state.teams[0].forEach(function(e,i){if(!e)return;state.active[0]=i;load(0,e);sides[0].find('.percent-hp').val(100).trigger('change');sides[0].find('.status').val('Healthy').trigger('change');sides[0].find('.boost').val(0);state.teams[0][i]=snapshot(0);});state.active[0]=0;load(0,state.teams[0][0]);apply($('.field-info'),baselineField);busy=false;save();render();performCalculations();message('Nueva batalla. Tu equipo está listo; puedes deshacer este reinicio.');});
 $('#undo').on('click',function(){if(!undo)return;busy=true;state=undo;undo=null;restoreState();busy=false;save();performCalculations();message('Batalla anterior recuperada.');});
 function download(data){var url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='battle-desk-backup.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
 $('#backup').on('click',function(){save();download(state);message('Copia descargada: incluye ambos equipos, notas y campo.');});$('#restore').on('click',function(){$('#backup-file').click();});
 function validate(x){if(!x||x.version!==1||!Array.isArray(x.teams)||x.teams.length!==2||!Array.isArray(x.active)||x.active.length!==2||x.active.some(function(i){return !Number.isInteger(i)||i<0||i>5;}))throw Error('Formato de copia no válido.');x.teams.forEach(function(team){if(!Array.isArray(team)||team.length!==6)throw Error('Equipo inválido.');team.forEach(function(e){if(e===null)return;if(typeof e.set!=='string'||typeof e.name!=='string'||!pokedex[e.name]||!Array.isArray(e.values)||e.values.length!==controls(sides[0]).length||typeof e.note!=='string'||!Array.isArray(e.confirmed)||e.confirmed.length!==5||!Number.isFinite(e.hp)||e.hp<0||e.hp>100||!Number.isFinite(e.maxHP)||e.maxHP<1)throw Error('Datos de Pokémon inválidos.');e.values.forEach(function(v){if(!v||!(typeof v.v==='string'||v.v===null||Array.isArray(v.v))||typeof v.c!=='boolean')throw Error('Control inválido.');});});});if(x.field!==null&&(!Array.isArray(x.field)||x.field.length!==controls($('.field-info')).length))throw Error('Campo inválido.');return x;}
 $('#backup-file').on('change',async function(){var file=this.files[0];this.value='';if(!file)return;try{if(file.size>2000000)throw Error('Copia demasiado grande.');var next=validate(JSON.parse(await file.text()));if(!confirm('¿Reemplazar la sesión actual por esta copia?'))return;save();undo=clone(state);busy=true;state=next;restoreState();busy=false;save();performCalculations();message('Copia restaurada.');}catch(e){busy=false;message('No se restauró la copia: '+e.message);}});
 function restoreState(){for(var s=0;s<2;s++)load(s,state.teams[s][state.active[s]]);if(state.field)apply($('.field-info'),state.field);refreshWidgets($('.field-info'));render();}
 $(document).on('keydown',function(e){if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;var n=Number(e.code&&e.code.replace('Digit',''));if(n>=1&&n<=6&&(e.altKey||e.shiftKey)){e.preventDefault();switchSlot(e.altKey?0:1,n-1);}});
 $('body').append('<dialog id="export-dialog" class="desk-dialog"><h2>Exportar set</h2><p>Formato Showdown. Selecciona y copia el texto. Para conservar también notas, PS y campo, usa Copia de seguridad.</p><textarea id="export-text" aria-label="Set exportado" readonly></textarea><div class="desk-actions"><button id="close-export">Cerrar</button></div></dialog>');
 $('#exportL,#exportR').text('Exportar set').off('click').on('click',function(){var s=this.id==='exportL'?0:1;if(!state.teams[s][state.active[s]]){message('Primero añade un Pokémon a ese espacio.');return;}ExportPokemon(sides[s]);$('#export-text').val($('textarea.import-team-text').val());document.getElementById('export-dialog').showModal();$('#export-text').focus().select();});$('#close-export').on('click',function(){document.getElementById('export-dialog').close();});
 sides[1].on('change.desk-confirm','.item,.move-selector',function(){if(busy)return;var e=state.teams[1][state.active[1]];if(!e)return;var index=$(this).hasClass('item')?0:sides[1].find('.move-selector').index(this)+1;e.confirmed[index]=false;render();});
 clearField();baselineField=capture($('.field-info'));var saved;try{saved=localStorage.getItem(KEY);if(saved)state=validate(JSON.parse(saved));}catch(e){message('La sesión guardada no es compatible. Puedes restaurar una copia.');saved=null;}
 var seed='Garchomp @ Choice Scarf\nAbility: Rough Skin\nEVs: 252 Atk / 4 Def / 252 Spe\nJolly Nature\n- Earthquake\n- Dragon Claw\n- Stone Edge\n- Fire Fang\n\nSlowbro @ Rocky Helmet\nAbility: Regenerator\nEVs: 252 HP / 252 Def / 4 SpD\nIVs: 0 Spe\nRelaxed Nature\n- Scald\n- Ice Beam\n- Teleport\n- Slack Off\n\nHeatran @ Leftovers\nAbility: Flash Fire\nEVs: 252 HP / 4 SpA / 252 SpD\nCalm Nature\n- Stealth Rock\n- Magma Storm\n- Taunt\n- Toxic\n\nZapdos @ Leftovers\nAbility: Pressure\nEVs: 252 SpA / 4 SpD / 252 Spe\nTimid Nature\n- Volt Switch\n- Hurricane\n- Hidden Power Ice\n- Roost\n\nStarmie @ Life Orb\nAbility: Analytic\nEVs: 252 SpA / 4 SpD / 252 Spe\nTimid Nature\n- Rapid Spin\n- Surf\n- Ice Beam\n- Thunderbolt\n\nScizor @ Choice Band\nAbility: Technician\nEVs: 248 HP / 252 Atk / 8 SpD\nAdamant Nature\n- Bullet Punch\n- U-turn\n- Pursuit\n- Superpower';
 try{if(saved)restoreState();else importTeam(seed,0);}catch(e){message('No se pudo precargar el equipo: '+e.message);}busy=false;render();save();performCalculations();window.addEventListener('beforeunload',save);
 window.BattleDesk={getState:function(){save();return clone(state);},switchSlot:switchSlot,parseTeam:parseTeam,importTeam:importTeam,validate:validate};
 if(document.modelContext&&document.modelContext.registerTool){try{document.modelContext.registerTool({name:'read_battle_session',description:'Leer equipos, espacios activos y notas guardadas; no modifica la sesión.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:function(){return clone(state);}});}catch(e){/* Optional browser capability. */}}
});
